services:
  db:
    image: postgres:18
    container_name: safenotes-postgres
    environment:
      POSTGRES_USER: safenotes
      POSTGRES_PASSWORD: safenotes
      POSTGRES_DB: safenotesdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: